# Generated by Django 5.0.7 on 2024-08-03 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Metadata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.TextField(unique=True)),
                ('descripcion', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Servicios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clase', models.CharField(max_length=100)),
                ('descripcion', models.TimeField(blank=True, null=True)),
                ('precio', models.FloatField(blank=True, null=True)),
                ('urlimagen', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
