# Generated by Django 5.0.7 on 2024-08-04 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_servicios_habilitado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Citas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('servicio', models.CharField(max_length=100)),
                ('descripcion', models.TextField()),
            ],
        ),
    ]
