# Generated by Django 5.0.7 on 2024-08-04 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_citas'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='importe',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
