# Generated by Django 5.0.7 on 2024-08-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_citas_importe'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='factura',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
