# Generated by Django 5.0.7 on 2024-08-04 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_citas_factura'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fechas_Bloqueadas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(unique=True)),
            ],
        ),
    ]
