# Generated by Django 5.0.7 on 2024-08-04 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_fechas_bloqueadas'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='hora',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
