# Generated by Django 5.0.7 on 2024-08-04 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_citas_hora'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='finalizada',
            field=models.BooleanField(default=False),
        ),
    ]
