# Generated by Django 5.0.7 on 2024-08-04 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0008_citas_finalizada'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='aprobada',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='citas',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
