# Generated by Django 5.0.7 on 2024-08-04 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0009_citas_aprobada_alter_citas_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
    ]
