# Generated by Django 5.0.7 on 2024-08-04 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_citas_name_citas_phone_citas_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='citas',
            old_name='name',
            new_name='nombre',
        ),
    ]
