# Generated by Django 5.0.7 on 2024-08-07 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_citas_nueva'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='cancelada',
            field=models.BooleanField(default=False),
        ),
    ]
