# Generated by Django 5.0.7 on 2024-08-08 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0016_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='fecha',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
