# Generated by Django 5.0.7 on 2024-08-08 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_mensaje_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='fecha',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
