# Generated by Django 5.0.7 on 2024-08-17 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0018_alter_mensaje_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='asunto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
